### ISSUE TITLE
Spawning 100s of processes

### ISSUE THREAD

**Issue by ramblingenzyme** [muse/Captain#11]
Since I synced with master to try out the feature added in #10, having "captain &" at the end of my bspwmrc has caused it to create and destroy 100's of processes, leading to close to 100% CPU usage. I have just about no clue why, because killing all of the processes and launching "captain &" in a terminal did not cause this problem.

**Comment by neeasade** [comment]
this would happen if the reload command you were watching for to launch things outputted many lines really fast -- is this with defaults in repo? I wonder if the bspc subscribe call outputs lots of lines as the bspwmrc concludes, unsure.

**Comment by ramblingenzyme** [comment]
That makes sense, and I seem to have pinpointed the culprit to `pactl subscribe`, so...this is might not be an issue. It was leaving lots of processes around in memory though, so something to keep in mind I guess?

**Comment by neeasade** [comment]
yeah, had not considered that problem previously, hm.

**Comment by neeasade** [comment]
so, on start, does pactl subscribe output vary? perhaps in recieving script you could filter for desired output before printing -- that would solve the 100's of unwanted processes if they were caused by misc startup info being printed.
