### ISSUE TITLE
Multihead/geometry features

### ISSUE THREAD

**Issue by neeasade** [muse/Captain#2]
Dropping off some ideas to consider/interest gauge on your end (may be totes out of scope)
- [x] gaps setting (done-ish with the offset setting I noticed, and this could be done via -g flag as well)
- [x] optional geometry flag to pass along to -g in lemonbar in captainrc
- [x] ability to point at one or all monitors in captainrc and have it 'just werk' 
- [x] an option to encapsulate sections with text or something(think powerline)
  - This could be done from the scripts, but what if I wanted to switch order around/sides without changing powerline arrow direction
  - edit: thoughts: would be in the bar section, something like `<align><left|right>append`. names are hard.

**Comment by muse** [comment]
- gaps setting
  Seems doable, I'll look at this.
- optional geometry flag to pass along to -g in lemonbar in captainrc
  How would you want to see this implemented, not entirely sure what you mean with this.
- ability to point at one or all monitors in captainrc
  It's in the `planned` section.
- an option to encapsulate sections with text or something (think powerline).
  Not sure what you mean with this, please explain further.

**Comment by neeasade** [comment]
- geometry flag

a setting in the [bar] section called geometry, that would take a setting like 1000x30+10+10, to pass along to the -g flag for lemonbar. Use case is to force location if you want.

on the text encapsulation, I'll continue the powerline example. 

say I wanted all my left scripts to have the powerline > on the right side, without having to go to each script I plan to have on the left echo the powerline > after they're done. would be nice to have a meta option in maybe the [bar] section, something like `left_surround = @>`, where @ would represent the content of the script. then I would do the same for the right side, as there I would want the powerline < on the left side of my script outputs.

**Comment by neeasade** [comment]
The items in this feature request are now covered by my captain fork(lemonade) in dotfiles. 

https://github.com/neeasade/dotfiles/tree/master/wm/.wm/panel

**Comment by roqstr** [comment]
hey @neeasade ,

could you explain why you forked captain and what your fork adds featurewise? Captain doesn't seem to be actively maintained and I'd love to switch over if it seems "worthy". Why don't you create a seperate repo for lemonade?

thanks!

**Comment by neeasade** [comment]
Hi, 

>  explain why you forked captain and what your fork adds featurewise?

I forked it primarily to add the features addressed in OP of this issue. 

other changes:
- scripts can be any language
- only targets bspwm-git and uses jq
- remove manual mode
- some performance improvements (some of these will only mean anything to @muse)
  - note enabled scripts and only run those (instead of looping through all treasures everytime)
  - only build the dynamic switch once on startup, not everytime in format() 
- lemon puns everywhere
- can have one rc file (juicer) per monitor. 

> I'd love to switch over if it seems "worthy". Why don't you create a seperate repo for lemonade?

My goal is currently not to make something "worthy", only something that integrates well with my dots. This may change in the future, but for now it will reside in my dotfiles. You are free to extract and put in a repo to use/mess around with. 

Thanks,
neeasade

**Comment by roqstr** [comment]
> only targets bspwm-git and uses jq

So I might get things wrong here (and I totally don't know if this is the right place to discuss this overall) but does this mean your fork wont properly/flawlessly work on any other wm than bspwm?

**Comment by neeasade** [comment]
Correct
