### ISSUE TITLE
Space between scripts

### ISSUE THREAD

**Issue by ufUNnxagpM** [muse/Captain#7]
As seen in the image below, there are spaces between scripts which makes powerline unusable if more than 1 script is used. A way to toggle/specify this would be nice (unless it's something to do with my setup).
![2016-01-08-161719_1920x1080_scrot](https://cloud.githubusercontent.com/assets/12422133/12212841/c2014036-b623-11e5-9169-507334a45f49.png)

**Comment by neeasade** [comment]
@CousinMachu you can just not put in the ':' characters in your format definition.

**Comment by ufUNnxagpM** [comment]
Thanks
